apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: ashokit
data:
  .dockerconfigjson:  ewoJImF1dGhzIjogewoJCSJhc2hva2l0Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJZWE5vYjJ0cGRDNWpiR0Z6YzJWelFHZHRZV2xzTG1OdmJUcEtabkp2WjJGemFHOXJhWFF4IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson